### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vetrivelmp** [GregFinzer/Compare-Net-Objects#128] opened 2018-12-17 10:02 UTC
Hello All,

 public static List<Difference> Compare(dynamic object1, dynamic object2, List<string> membersToIgnore = null)
        {
            List<Difference> differences = new List<Difference>();

            //Set Comparision cofig
            CompareLogic compareLogic = new CompareLogic();
            compareLogic.Config = new ComparisonConfig()
            {
                CaseSensitive = false,
                MaxDifferences = 50,
                MembersToIgnore = membersToIgnore,
                IgnoreCollectionOrder = true,
                CompareChildren = true
            };

            ComparisonResult result = compareLogic.Compare(object1, object2);

            if (result != null && result.Differences != null && result.Differences.Count > 0)
            {
                foreach (var difference in result.Differences)
                {
                    //Create custom difference object to return to UI
                    differences.Add(new Difference()
                    {
                        PropertyName = difference.PropertyName,
                        ActualValue = difference.Object1Value,
                        AlteredValue = difference.Object2Value
                    });
                }
            }

            return differences;
        }

When i pass argument as List<T>, i  am getting Object reference not set to an instance of an object.

Please let me know what i am missing.

**Comment by GregFinzer** [comment] 2018-12-17 12:37
Sorry, Compare .NET Objects does not support dynamic objects.  This is a duplicate of this issue:
https://github.com/GregFinzer/Compare-Net-Objects/issues/103

**Closed by GregFinzer** 2018-12-17 12:37 UTC

**Comment by vetrivelmp** [comment] 2018-12-18 04:49
Even though i changed to argument type object. the same error i am getting the same error.
 public static List<Difference> Compare(object object1, object object2, List<string> membersToIgnore = null)
